// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQ47ZIwUP8Enq5SLldd_Sek2UiZXLEr0',
    appId: '1:730811119826:android:4534b17a347be4ae13d50b',
    messagingSenderId: '730811119826',
    projectId: 'one_pidilite-5a845',
    storageBucket: 'one_pidilite-5a845.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMEHqF-anVTkLQTqWaUFip2fHVsWV0Qtw',
    appId: '1:730811119826:ios:fbd76395a9dc630613d50b',
    messagingSenderId: '730811119826',
    projectId: 'one_pidilite-5a845',
    storageBucket: 'one_pidilite-5a845.firebasestorage.app',
    iosBundleId: 'com.nebula.one_pidilite',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8gkdeCyVpZrHg_wHAAbD-xEpFCBIiSQ',
    appId: '1:629422214139:web:b5c0d423cafade6c11995e',
    messagingSenderId: '629422214139',
    projectId: 'one_pidilite-ab574',
    authDomain: 'one_pidilite-ab574.firebaseapp.com',
    storageBucket: 'one_pidilite-ab574.firebasestorage.app',
    measurementId: 'G-60Y3TTSLZ4',
  );

}